# Generated by Django 3.1.3 on 2020-11-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_activeusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveUsers',
            new_name='ActiveUser',
        ),
    ]
